# Generated by Django 5.0.1 on 2024-01-11 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step1', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grain', models.CharField(max_length=90)),
                ('date', models.DateField(max_length=130)),
                ('store', models.TextField(max_length=500)),
                ('fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soyabean.process')),
            ],
        ),
    ]
